### ISSUE TITLE
Node should halt on password error

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuel-js#9]
When entering a less-than-8 character passphrase, the node should halt immediately instead of continuing until a different error is hit.

```
✔ Please enter a Fuel wallet encryption passphrase … ***
Error: password must be more than 8 characters
    at wallet (/snapshot/client/src/wallet.js:68:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
fuel-2021-01-04 7:36:35 PM : Wallet/operator address used: undefined
fuel-2021-01-04 7:36:35 PM : DB: default local db selected.
{ Error: invalid private key (arg="privateKey", reason="exactly 32 bytes required", value="[REDACTED]", length=10, type="string", version=4.0.48)
    at Object.throwError (/snapshot/client/node_modules/ethers/errors.js:76:17)
    at new SigningKey (/snapshot/client/node_modules/ethers/utils/signing-key.js:50:20)
    at new Wallet (/snapshot/client/node_modules/ethers/wallet.js:44:62)
    at config (/snapshot/client/src/config.local.js:178:24)
    at app (/snapshot/client/src/app.js:74:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  reason: 'exactly 32 bytes required',
  code: 'INVALID_ARGUMENT',
  arg: 'privateKey',
  value: '[REDACTED]',
  length: 10,
  type: 'string' }
attempting exit
```

**Comment by SilentCicero** [comment]
Better error handing will be available in: https://github.com/FuelLabs/fuel-js/pull/12
